FROM node:24-alpine

RUN apk add --no-cache python3 make g++ && \
    npm install -g nx @nrwl/cli

COPY --chown=node:node . /usr/src/app

WORKDIR /usr/src/app
RUN rm -rf node_modules
RUN npm install --force --loglevel verbose

CMD ["sh", "-c", "nx serve client-service"]
